### ISSUE TITLE
References to CloudFormation templates are broken in clickhouse-entrypoint-new-vpc.template.yaml

### ISSUE THREAD

**Issue by harryxpan** [aws-quickstart/quickstart-clickhouse-cluster#24]
I was trying to deploy clickhouse-entrypoint-new-vpc.template.yaml in us-west-2, and soon realized that it references other CloudFormation templates that do not exist anymore.  For example, after resolution this one (line 556)

https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml

becomes

https://aws-quickstart.s3.us-east-1.amazonaws.com/quickstart-clickhouse-cluster/submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml

which is a broken link.

Other links starting with https://${S3Bucket} also have similar issues.

**Comment by troy-ameigh** [comment]
Henry thank you for your issue. These links are not broken, the Quick Start is designed to be launched from S3 buckets once published. This Quick Start is still in beta, so to deploy it from git you will need to clone it to your local machine, and the run the following command. 

git submodule update --init --recursive

once the submodules are pulled in, you can then copy the whole folder up to S3 so you can launch the entrypoint template, using the S3 ARN.

**Comment by harryxpan** [comment]
Thanks Troy.  Problem solved.
